
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftIDSTRleftCREATEleftSENDleftCLOSEleftIPCLOSE COMMENT CREATE ID IP SEND STR\n    program : statement\n            | empty\n    statement : CREATE ID IPstatement : SEND STRstatement : CLOSEempty :'
    
_lr_action_items = {'CREATE':([0,],[4,]),'SEND':([0,],[5,]),'CLOSE':([0,],[6,]),'$end':([0,1,2,3,6,8,9,],[-6,0,-1,-2,-5,-4,-3,]),'ID':([4,],[7,]),'STR':([5,],[8,]),'IP':([7,],[9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement':([0,],[2,]),'empty':([0,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement','program',1,'p_program','networkyacc.py',20),
  ('program -> empty','program',1,'p_program','networkyacc.py',21),
  ('statement -> CREATE ID IP','statement',3,'p_statement1','networkyacc.py',26),
  ('statement -> SEND STR','statement',2,'p_statement2','networkyacc.py',33),
  ('statement -> CLOSE','statement',1,'p_statement3','networkyacc.py',39),
  ('empty -> <empty>','empty',0,'p_empty','networkyacc.py',44),
]
